### ISSUE TITLE
Restructuring v0.6.1 Borealis file with BorealisRestructure class

### ISSUE THREAD

**Issue by tjk584** [SuperDARN/pyDARNio#50]
# BUG 

Unable to restructure Borealis 0.6.1 antennas_iq file using the BorealisRestructure class

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [X] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Example of the bug 

Converting antennas_iq file produced from Borealis v0.6.1 on INV:

```
python3 borealis_convert_file.py --low_memory 20221104.1400.00.inv.0.antennas_iq.hdf5.site
Traceback (most recent call last):
  File "/home/transfer/data_flow/site-linux/borealis_convert_file.py", line 264, in <module>
    main()
  File "/home/transfer/data_flow/site-linux/borealis_convert_file.py", line 233, in main
    low_memory)
  File "/home/transfer/data_flow/site-linux/borealis_convert_file.py", line 191, in borealis_site_to_array_file
    outfile_structure='array', hdf5_compression='zlib')
  File "/home/transfer/pydarnio-env/lib/python3.6/site-packages/pydarnio/borealis/borealis_restructure.py", line 136, in __init__
    self.software_version][self.borealis_filetype]
KeyError: 'v0.6.1'
```

### Data Location

Antennas_iq files available on INV NAS.

**Comment by RemingtonRohel** [comment]
Hey Theo, I made a branch to fix this problem but I run into another one afterwards. Can you try with your data file and see if you it works for you? If so, I think my error is unrelated and I will address it in another issue.

The changes I made are on branch https://github.com/SuperDARN/pyDARNio/tree/bugfix/restructure_version

**Comment by tjk584** [comment]
Tested on RKN dataflow, logfile below shows conversion is working:

```
Converting /borealis_nfs/borealis_data/daily/20221109.1000.00.rkn.0.antennas_iq.hdf5.site
python3 remove_record.py 20221109.1000.00.rkn.0.antennas_iq.hdf5.site
python3 borealis_convert_file.py --low_memory 20221109.1000.00.rkn.0.antennas_iq.hdf5.site
Wrote array to: /borealis_nfs/borealis_data/daily/20221109.1000.00.rkn.0.antennas_iq.hdf5
Conversion time: 291.30 seconds
renamed '/borealis_nfs/borealis_data/daily/20221109.1000.00.rkn.0.antennas_iq.hdf5' -> '/borealis_nfs/borealis_data/antennas_iq_array/20221109.1000.00.rkn.0.antennas_iq.hdf5'
removed '/borealis_nfs/borealis_data/daily/20221109.1000.00.rkn.0.antennas_iq.hdf5.site'
Successfully converted: /borealis_nfs/borealis_data/daily/20221109.1000.00.rkn.0.antennas_iq.hdf5.site

Converting /borealis_nfs/borealis_data/daily/20221109.0600.00.rkn.1.antennas_iq.hdf5.site
python3 remove_record.py 20221109.0600.00.rkn.1.antennas_iq.hdf5.site
python3 borealis_convert_file.py --low_memory 20221109.0600.00.rkn.1.antennas_iq.hdf5.site
Wrote array to: /borealis_nfs/borealis_data/daily/20221109.0600.00.rkn.1.antennas_iq.hdf5
Conversion time: 249.23 seconds
renamed '/borealis_nfs/borealis_data/daily/20221109.0600.00.rkn.1.antennas_iq.hdf5' -> '/borealis_nfs/borealis_data/antennas_iq_array/20221109.0600.00.rkn.1.antennas_iq.hdf5'
removed '/borealis_nfs/borealis_data/daily/20221109.0600.00.rkn.1.antennas_iq.hdf5.site'
Successfully converted: /borealis_nfs/borealis_data/daily/20221109.0600.00.rkn.1.antennas_iq.hdf5.site
```
